USE [master]
GO
/****** Object:  Database [TranferLearningML]    Script Date: 11/4/2024 10:41:55 PM ******/
CREATE DATABASE [TranferLearningML]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TranferLearningML', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TranferLearningML.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TranferLearningML_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TranferLearningML_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TranferLearningML] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TranferLearningML].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TranferLearningML] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TranferLearningML] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TranferLearningML] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TranferLearningML] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TranferLearningML] SET ARITHABORT OFF 
GO
ALTER DATABASE [TranferLearningML] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [TranferLearningML] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TranferLearningML] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TranferLearningML] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TranferLearningML] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TranferLearningML] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TranferLearningML] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TranferLearningML] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TranferLearningML] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TranferLearningML] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TranferLearningML] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TranferLearningML] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TranferLearningML] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TranferLearningML] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TranferLearningML] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TranferLearningML] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TranferLearningML] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TranferLearningML] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TranferLearningML] SET  MULTI_USER 
GO
ALTER DATABASE [TranferLearningML] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TranferLearningML] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TranferLearningML] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TranferLearningML] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TranferLearningML] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TranferLearningML] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TranferLearningML] SET QUERY_STORE = ON
GO
ALTER DATABASE [TranferLearningML] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TranferLearningML]
GO
/****** Object:  Table [dbo].[ImageData]    Script Date: 11/4/2024 10:41:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImageData](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ImagePath] [nvarchar](max) NULL,
	[Label] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ImagePrediction]    Script Date: 11/4/2024 10:41:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImagePrediction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ImageDataId] [int] NULL,
	[Score] [nvarchar](max) NULL,
	[PredictedLabelValue] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ImagePrediction]  WITH CHECK ADD FOREIGN KEY([ImageDataId])
REFERENCES [dbo].[ImageData] ([Id])
GO
USE [master]
GO
ALTER DATABASE [TranferLearningML] SET  READ_WRITE 
GO
